// API behavior tests use disposable in-memory fixtures, never college records.
const test=require('node:test'),assert=require('node:assert/strict'),jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs');
process.env.JWT_SECRET='test-only-key-for-disposable-fixtures';
const demo=require('../services/demoCampus')();
const profiles=demo.students.slice(0,2).map((s,i)=>({id:101+i,user_id:3+i,student_id:'TEST'+(101+i),campusId:'TEST'+(101+i),department:s.department,year:s.year,name:'Fixture student '+(i+1),email:'fixture'+i+'@example.invalid',cgpa:s.data.academic.cgpa}));
const accounts={1:{id:1,email:'admin@example.invalid',role:'ADMIN',status:'APPROVED',session_version:1},2:{id:2,email:'faculty@example.invalid',role:'FACULTY',department:'CSE',status:'APPROVED',session_version:1},3:{id:3,email:'student@example.invalid',role:'STUDENT',status:'APPROVED',session_version:1}};
let state={records:[],batches:[],interventions:[],events:[],audit:[]};
const baseRows={academic_data:[],attendance:[],lms_activity:[],engagement:[],placement:[],skills:[],feedback:[],student_performance:[],performance_submissions:[],agent_observations:[]};
const mapping={academic_data:['academic',{marks:'average_marks',backlogs:'backlogs',subjectPerformance:'subject_performance'}],attendance:['attendance',{overall:'overall_percentage',subjects:'subject_wise'}],lms_activity:['lms',{loginFrequency:'login_frequency',assignmentCompletion:'assignment_completion',learningActivity:'learning_activity'}],engagement:['engagement',{events:'events_score',clubs:'clubs_score',hackathons:'hackathon_score',certifications:'certification_score'}],placement:['placement',{coding:'coding_score',aptitude:'aptitude_score',interview:'mock_interview_score',readiness:'readiness_score'}],skills:['skills',{technical:'technical_score',soft:'soft_skill_score',assessment:'assessment_score'}],feedback:['feedback',{satisfaction:'student_satisfaction',faculty:'faculty_feedback'}]};
for(const [table,[category,fields]]of Object.entries(mapping))profiles.forEach((p,i)=>baseRows[table].push({id:p.id,student_id:p.id,...Object.fromEntries(Object.entries(fields).map(([from,to])=>[to,demo.students[i].data[category][from]]))}));
function duplicate(){const e=new Error('Duplicate fixture');e.code='ER_DUP_ENTRY';throw e;}
async function query(sql,args=[],store=state){
 if(sql.startsWith('SELECT u.id,u.email,u.role'))return [[accounts[args[0]]].filter(Boolean)];
 if(sql==='SELECT 1')return [[{ok:1}]];
 if(sql.startsWith('SELECT s.id,s.user_id')){
  let rows=profiles.slice();let p=0;if(sql.includes('s.user_id=?')){const id=args[p++];rows=rows.filter(s=>s.user_id===id);}else if(sql.includes('s.department=?')){const department=args[p++];rows=rows.filter(s=>s.department===department);}if(sql.includes('AND s.id=?'))rows=rows.filter(s=>s.id===Number(args[p]));return [rows];
 }
 if(sql.startsWith('SELECT department FROM students'))return [profiles.filter(s=>s.id===Number(args[0])).map(s=>({department:s.department}))];
 if(sql.startsWith('SELECT * FROM student_source_records'))return [store.records.filter(r=>args.includes(r.student_id))];
 if(sql.startsWith('SELECT * FROM')){const table=sql.match(/SELECT \* FROM (\w+)/)[1];if(Object.hasOwn(baseRows,table))return [baseRows[table].filter(r=>args.includes(r.student_id))];}
 if(sql.startsWith('SELECT id FROM interventions'))return [store.interventions.filter(r=>r.student_id===args[0]&&r.title===args[1]&&['ASSIGNED','IN_PROGRESS'].includes(r.status))];
 if(sql.startsWith('INSERT INTO source_import_batches')){if(store.batches.some(b=>b.hash===args[1]))duplicate();const id=store.batches.length+1;store.batches.push({id,hash:args[1]});return [{insertId:id}];}
 if(sql.startsWith('INSERT INTO student_source_records')){if(store.records.some(r=>r.record_hash===args[7]))duplicate();const id=store.records.length+1;store.records.push({id,batch_id:args[0],student_id:args[1],category:args[2],indicator_values:args[3],source_reference:args[4],measured_at:args[5],verified_by:args[6],record_hash:args[7]});return [{insertId:id}];}
 if(sql.startsWith('INSERT INTO review_audit')){store.audit.push(args);return [{insertId:store.audit.length}];}
 if(sql.startsWith('INSERT INTO interventions')){const id=store.interventions.length+1;store.interventions.push({id,student_id:args[0],assigned_by:args[1],title:args[2],description:args[3],status:'ASSIGNED'});return [{insertId:id}];}
 if(sql.startsWith('INSERT INTO agent_intervention_events')){store.events.push(args);return [{insertId:store.events.length}];}
 throw new Error('Unhandled fixture query: '+sql);
}
const fake={query,getConnection:async()=>{let tx;return {beginTransaction:async()=>{tx=structuredClone(state);},query:(s,a)=>query(s,a,tx),commit:async()=>{state=tx;},rollback:async()=>{},release:()=>{}};}};
const dbPath=require.resolve('../config/db');require.cache[dbPath]={id:dbPath,filename:dbPath,loaded:true,exports:fake};
const app=require('../index');let server,base;
test.before(async()=>{server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));base='http://127.0.0.1:'+server.address().port;});
test.after(async()=>{await new Promise(resolve=>server.close(resolve));});
const tokens=Object.fromEntries(Object.entries(accounts).map(([id,a])=>[a.role,jwt.sign({id:Number(id),role:a.role,sessionVersion:1},process.env.JWT_SECRET)]));
async function request(path,role='ADMIN',body){const response=await fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(role?{Authorization:'Bearer '+tokens[role]}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();return {status:response.status,data};}
const record={studentId:'TEST101',category:'placement',source:'Disposable fixture coding assessment',measuredAt:'2026-09-01T09:00:00Z',values:{coding:24}};
test('demo is public and explicitly synthetic; protected overview requires authentication',async()=>{const d=await request('/api/success/demo',null);assert.equal(d.status,200);assert.equal(d.data.mode,'DEMO');assert.equal(d.data.students.length,6);assert.equal((await request('/api/success/overview',null)).status,401);});
test('administrator sees all students; faculty and student scopes are enforced',async()=>{assert.equal((await request('/api/success/overview')).data.students.length,2);const f=await request('/api/success/overview','FACULTY');assert.equal(f.data.students.length,1);assert.equal(f.data.students[0].department,'CSE');const s=await request('/api/success/overview','STUDENT');assert.equal(s.data.students.length,1);assert.equal(s.data.students[0].id,101);});
test('student cannot import or assign support; faculty cannot import other departments',async()=>{assert.equal((await request('/api/success/imports','STUDENT',{records:[record]})).status,403);assert.equal((await request('/api/success/students/101/recommendations/coding','STUDENT',{})).status,403);const r=await request('/api/success/imports','FACULTY',{records:[{...record,studentId:'TEST102'}]});assert.equal(r.data.canCommit,false);assert(r.data.errors.length);});
test('preview is read-only and commit requires explicit verification',async()=>{const count=state.records.length,r=await request('/api/success/imports','FACULTY',{records:[record]});assert.equal(r.status,200);assert.equal(r.data.canCommit,true);assert.equal(state.records.length,count);assert.equal((await request('/api/success/imports','FACULTY',{records:[record],commit:true})).status,400);});
test('verified commit updates unified records and audit; duplicate retry saves nothing',async()=>{const body={records:[record],commit:true,verified:true,verificationNote:'Disposable test evidence only'},r=await request('/api/success/imports','FACULTY',body);assert.equal(r.status,201);assert.equal(state.records.length,1);assert.equal(state.audit.length,1);const overview=await request('/api/success/overview','FACULTY');assert.equal(overview.data.students[0].data.placement.coding,24);assert.equal(overview.data.students[0].provenance['placement.coding'].source,record.source);assert.equal((await request('/api/success/imports','FACULTY',body)).status,409);assert.equal(state.records.length,1);});
test('overlapping duplicate inside another batch rolls back every record',async()=>{const body={records:[{...record,studentId:'TEST102',values:{coding:88}},record],commit:true,verified:true,verificationNote:'Disposable fixture batch'};const r=await request('/api/success/imports','ADMIN',body);assert.equal(r.status,409);assert.equal(state.records.length,1);assert.equal(state.batches.length,1);});
test('assignment is scoped, creates an event, and prevents active duplicates',async()=>{assert.equal((await request('/api/success/students/102/recommendations/coding','FACULTY',{})).status,403);const r=await request('/api/success/students/101/recommendations/coding','FACULTY',{});assert.equal(r.status,201);assert.equal(state.interventions.length,1);assert.equal(state.events.length,1);assert.equal((await request('/api/success/students/101/recommendations/coding','FACULTY',{})).status,409);});
test('existing roster endpoint shares the unified success calculation',async()=>{const a=await request('/api/students','FACULTY'),b=await request('/api/success/overview','FACULTY');assert.equal(a.status,200);assert.equal(a.data.students[0].success_score,b.data.students[0].successScore);});
test('render server serves original workspace plus enhancement and required deliverables',async()=>{for(const path of ['/','/style.css','/script.js','/success-assets/score-note.html','/success-assets/demo-slides.html','/success-assets/import-template.csv']){const response=await fetch(base+path);assert.equal(response.status,200,path);const text=await response.text();assert(text.length>100,path);}const response=await fetch(base+'/script.js');assert((await response.text()).includes('successOverview'));});
